### ISSUE TITLE
Multisite WP unfilter_html issue

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/odm-frontend#2]
MWP does not allow any kind of users, even (admin/editor users) to post HTML markup or even JavaScript code in pages, posts, comments and widgets. Only a user Super Admins have who manage the entire system, have the unfiltered_html capability. 
Most of the contents have the data visualizations that need to add html/js script that added by editor, so we can't set the role of them to be Super admin role. 

Note: Enabling this option for untrusted users may result in their posting malicious or poorly formatted code.

**Comment by Huyeng** [comment]
There is an plugin to gives Administrators and Editors the unfiltered_html capability. 
However, this plugin hasn't been updated in over 2 years. 
Link: https://wordpress.org/plugins/unfiltered-mu/

**Comment by mishari** [comment]
@Huyeng can this issue be closed?

**Comment by Huyeng** [comment]
Unfiltered-MU is decided to use for temporary, so the issue is fixed now.
