### ISSUE TITLE
Shortcode in caption shortcode not work

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/odm-frontend#71]
![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/20387131/44467f1a-acf1-11e6-89a1-1dd68d51f9cb.jpg)

**Comment by Huyeng** [comment]
The result should be like this:
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/20387294/fa0e4c7e-acf1-11e6-9df7-c764db87cb03.jpg)

**Comment by acorbi** [comment]
@Huyeng I have now created a separate repository for **reference-footnotes** on https://github.com/OpenDevelopmentMekong/reference-footnotes and added it a submodule to **odm-frontend** (see https://github.com/OpenDevelopmentMekong/odm-frontend/tree/master/wp-content/plugins)

This is now deployed both on PP and PROD. can you please check?
